# Generated by Django 4.1.3 on 2023-12-06 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kantin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kantin.menu')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mahasiswa', to=settings.AUTH_USER_MODEL)),
                ('penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kantin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Keranjang',
            },
        ),
    ]
