# Generated by Django 4.1.3 on 2023-12-13 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kantin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_cart', models.CharField(choices=[('Aktif', 'Aktif'), ('NonAktif', 'NonAktif')], default='Aktif', max_length=10)),
                ('jumlah_pesanan', models.PositiveIntegerField(default=0)),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Diterima', 'Diterima'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Diterima', max_length=10)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_pembeli', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pesanan', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kantin.menu')),
                ('penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kantin', to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.pesanan')),
            ],
            options={
                'db_table': 'Keranjang',
            },
        ),
    ]
