# Generated by Django 4.1.3 on 2023-12-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keranjang',
            old_name='jumlah',
            new_name='jumlah_pesanan',
        ),
    ]
