# Generated by Django 4.1.3 on 2023-12-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0002_rename_jumlah_keranjang_jumlah_pesanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keranjang',
            name='jumlah_pesanan',
        ),
        migrations.AddField(
            model_name='keranjang',
            name='jumlah',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
