# Generated by Django 4.1.3 on 2023-12-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0003_remove_keranjang_jumlah_pesanan_keranjang_jumlah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keranjang',
            old_name='jumlah',
            new_name='jumlah_pesanan',
        ),
    ]
