# Generated by Django 4.1.3 on 2023-12-09 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kantin', '0001_initial'),
        ('pesanan', '0004_rename_jumlah_keranjang_jumlah_pesanan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pesanan', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Diterima', 'Diterima'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Diterima', max_length=10)),
                ('kantin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_kantin', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kantin.menu')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan_pembeli', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
